name: CI for cs_books

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any other dependencies if required

    - name: Run process.py
      run: python process.py

    - name: Check for changes in README.md
      id: check_changes
      run: |
        git diff --exit-code README.md || echo "README.md has changes" && echo "::set-output name=changed::true"
      continue-on-error: true

    - name: Commit changes
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update README.md"

    - name: Create Pull Request
      if: steps.check_changes.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Update README.md"
        body: "Automated update of README.md"
        branch: "automated/readme-update"
